# These are supported funding model platforms

github: r0d1on # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
buy_me_a_coffee: r0d1on # Replace with a single Buy Me a Coffee username
patreon: r0d1on # Replace with a single Patreon username
